repos:
-   repo: local
    hooks:
    - id: gobuild
      name: gobuild
      entry: make build
      language: golang
      types: [go]
      require_serial: true
      pass_filenames: false
    - id: golangci-lint
      name: golint
      entry: make lint
      language: golang
      types: [go]
      require_serial: true
      pass_filenames: false
    - id: gotest
      name: gotest
      entry: make test
      language: golang
      types: [go]
      require_serial: true
      pass_filenames: false
